import { Inter } from "next/font/google";
import "../public/assets/sass/style.scss";
import "../public/assets/css/fontawesome.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../public/assets/css/slick.min.css";
import "../public/assets/js/main.js";
// import "../public/assets/js/slick.min.js";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
